# Generated by Django 4.2.5 on 2023-10-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0002_cartype_fueltype_alter_car_image_car_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
