# Generated by Django 4.2.5 on 2023-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0003_cancellationrequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
