# Generated by Django 4.2.5 on 2023-10-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0004_review_approved_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
