# Generated by Django 4.2.5 on 2023-10-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0007_rename_location_car_location_name_car_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Sports car', 'Sports car')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
    ]
