# Generated by Django 4.2.5 on 2023-10-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0012_contactformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
