# Generated by Django 4.2.5 on 2023-10-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0013_alter_payment_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
