# Generated by Django 4.2.5 on 2023-10-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0014_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Sports Car', 'Sports Car')], max_length=20, null=True),
        ),
    ]
