# Generated by Django 4.2.5 on 2023-10-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoR5', '0016_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Sports Car', 'Sports_Car')], max_length=20, null=True),
        ),
    ]
